version: "3.1"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  backend:
    container_name: backend
    build:
      dockerfile: ./app/Dockerfile
    image: node:16-alpine
    ports:
      - "3000:3000"
